import "../globals.css";
import type { Metadata } from "next";
import { M_PLUS_Rounded_1c } from "next/font/google";

const mplus = M_PLUS_Rounded_1c({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-mplus",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={mplus.variable}>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Kiwi+Maru&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans antialiased" style={{ fontFamily: '"Kiwi Maru", sans-serif', fontSize: "24px" }}>
        {children}
      </body>
    </html>
  );
}
